const STORAGE_KEY='amir-fitness-tracker-v1';
const seed={goalWeight:null,measurements:[],workouts:[],meals:[],targets:{calories:null,protein:null,carbs:null,fat:null}};
const localDate=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')};
let selectedDate=localDate();
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let editing=null;
let data=load();
let deferredPrompt=null;
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(data));document.querySelector('#notice').textContent='تم الحفظ';renderAll();return true}catch{document.querySelector('#notice').textContent='تعذر الحفظ على الجهاز. صدّر نسخة احتياطية الآن.';return false}}
function fmtDate(d){return new Intl.DateTimeFormat('ar-EG-u-ca-gregory',{day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'))}
function latest(){return [...data.measurements].sort((a,b)=>a.date.localeCompare(b.date)).at(-1)}
function previous(){const a=[...data.measurements].sort((x,y)=>x.date.localeCompare(y.date));return a.length>1?a.at(-2):null}
function delta(key,digits=1){const l=latest(),p=previous();if(!l||!p||l[key]==null||p[key]==null)return '—';const d=l[key]-p[key];return `${d>0?'+':''}${d.toFixed(digits)}`}
function renderDashboard(){const l=latest();if(!l){document.querySelector('#heroWeight').textContent='—';document.querySelector('#heroDate').textContent='سجل أول قياس لبدء المتابعة';document.querySelector('#metricCards').innerHTML='';document.querySelector('#goalProgress').textContent='—';document.querySelector('.goal-ring small').textContent=data.goalWeight?`نحو ${data.goalWeight} كجم`:'حدد هدفك';document.querySelector('.goal-ring').style.background='#152b24';drawChart();} if(l){document.querySelector('#heroWeight').textContent=`${l.weight.toFixed(1)} كجم`;document.querySelector('#heroDate').textContent=fmtDate(l.date);const start=[...data.measurements].sort((a,b)=>a.date.localeCompare(b.date))[0]?.weight||l.weight;const direction=data.goalWeight>start?1:-1;const total=Math.max(.1,Math.abs(start-data.goalWeight)),done=Math.max(0,(l.weight-start)*direction);const pct=Math.max(0,Math.min(100,Math.round(done/total*100)));document.querySelector('#goalProgress').textContent=data.goalWeight?`${pct}%`:'—';document.querySelector('.goal-ring small').textContent=data.goalWeight?`نحو ${data.goalWeight} كجم`:'حدد هدفك';document.querySelector('.goal-ring').style.background=`radial-gradient(circle at center,#0f172a 56%,transparent 57%),conic-gradient(#a3e635 0 ${data.goalWeight?pct:0}%,#334155 0)`;
 const metrics=[['BMI',l.bmi,delta('bmi')],['دهون الجسم',`${l.bfr}%`,`${delta('bfr')}%`],['كتلة الدهون',`${l.fatMass} كجم`,`${delta('fatMass')} كجم`],['وزن العضلات',`${l.muscleWeight} كجم`,`${delta('muscleWeight')} كجم`],['الماء',`${l.water}%`,`${delta('water')}%`],['BMR',`${l.bmr} kcal`,`${delta('bmr',0)} kcal`],['دهون حشوية',l.visceralFat,delta('visceralFat',0)],['وزن دون دهون',`${l.leanWeight} كجم`,`${delta('leanWeight')} كجم`]];
 document.querySelector('#metricCards').innerHTML=metrics.filter(m=>m[1]!=null&&!String(m[1]).includes('undefined')&&!String(m[1]).includes('null')).map(m=>`<div class="metric"><div class="label">${m[0]}</div><div class="value">${esc(m[1])}</div><div class="trend">التغير: ${m[2]}</div></div>`).join('');drawChart();}
 const today=selectedDate;const tw=data.workouts.filter(x=>x.date===today);document.querySelector('#todayWorkout').innerHTML=tw.length?tw.map(w=>`<div class="stack-item"><h4>${esc(w.exercise)}</h4><div class="chips">${w.sets.map((s,i)=>`<span class="chip">${i+1}: ${s.w} كجم × ${s.r}</span>`).join('')}</div></div>`).join(''):`<div class="empty">لا يوجد تمرين مسجل اليوم.</div>`;
 const tm=data.meals.filter(x=>x.date===today);const sums=sumMeals(tm);document.querySelector('#nutritionSummary').innerHTML=`<div class="chips"><span class="chip">${sums.calories} سعرة</span><span class="chip">بروتين ${sums.protein}غ</span><span class="chip">كارب ${sums.carbs}غ</span><span class="chip">دهون ${sums.fat}غ</span></div>`}
function drawChart(){const c=document.querySelector('#weightChart'),ctx=c.getContext('2d'),arr=[...data.measurements].sort((a,b)=>a.date.localeCompare(b.date));ctx.clearRect(0,0,c.width,c.height);document.querySelector('#chartHint').textContent=arr.length<2?'أضف قياسين على الأقل لعرض اتجاه الوزن.':'';if(arr.length<2)return;const pad=45,min=Math.min(...arr.map(x=>x.weight))-1,max=Math.max(...arr.map(x=>x.weight))+1;ctx.strokeStyle='#cbd5e1';ctx.lineWidth=1;for(let i=0;i<4;i++){const y=pad+i*(c.height-2*pad)/3;ctx.beginPath();ctx.moveTo(pad,y);ctx.lineTo(c.width-pad,y);ctx.stroke()}ctx.strokeStyle='#0ea5a8';ctx.lineWidth=5;ctx.lineJoin='round';ctx.beginPath();arr.forEach((m,i)=>{const x=pad+i*(c.width-2*pad)/(arr.length-1);const y=c.height-pad-(m.weight-min)/(max-min)*(c.height-2*pad);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();arr.forEach((m,i)=>{const x=pad+i*(c.width-2*pad)/(arr.length-1);const y=c.height-pad-(m.weight-min)/(max-min)*(c.height-2*pad);ctx.fillStyle='#0f172a';ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill();ctx.font='24px sans-serif';ctx.fillText(String(m.weight),x-22,y-14)})}
function renderWorkouts(){const list=document.querySelector('#workoutList');const arr=[...data.workouts].sort((a,b)=>b.date.localeCompare(a.date));list.innerHTML=arr.length?arr.map((w,i)=>`<div class="stack-item"><div class="stack-item-head"><div><h4>${esc(w.exercise)}</h4><p class="muted">${esc(w.group)} · ${fmtDate(w.date)}</p></div><button class="secondary" onclick="editRecord('workout',${i})">تعديل</button><button class="secondary" onclick="removeWorkout(${i})">حذف</button></div><div class="chips">${w.sets.map((s,n)=>`<span class="chip">مجموعة ${n+1}: ${s.w} كجم × ${s.r}</span>`).join('')}</div></div>`).join(''):`<div class="empty">ابدأ بإضافة أول تمرين.</div>`}
function sumMeals(arr){return arr.reduce((a,m)=>({calories:a.calories+(+m.calories||0),protein:a.protein+(+m.protein||0),carbs:a.carbs+(+m.carbs||0),fat:a.fat+(+m.fat||0)}),{calories:0,protein:0,carbs:0,fat:0})}
function renderNutrition(){const today=selectedDate,arr=data.meals.filter(m=>m.date===today),s=sumMeals(arr),items=[['السعرات',s.calories,data.targets.calories,'kcal'],['البروتين',s.protein,data.targets.protein,'غ'],['الكربوهيدرات',s.carbs,data.targets.carbs,'غ'],['الدهون',s.fat,data.targets.fat,'غ']];document.querySelector('#macroGrid').innerHTML=items.map(x=>`<div class="macro"><span class="muted">${x[0]}</span><strong>${Math.round(x[1]*10)/10} ${x[3]} <small>${x[2]?`/ ${x[2]}`:"بدون هدف"}</small></strong><div class="progress"><span style="width:${x[2]?Math.min(100,Math.round(x[1]/x[2]*100)):0}%"></span></div></div>`).join('');document.querySelector('#mealList').innerHTML=arr.length?arr.map((m,i)=>`<div class="stack-item"><div class="stack-item-head"><div><h4>${esc(m.name)}</h4><p class="muted">${esc(m.food)}</p></div><button class="secondary" onclick="editRecord('meal',${i})">تعديل</button><button class="secondary" onclick="removeMeal(${i})">حذف</button></div><div class="chips"><span class="chip">${m.calories} سعرة</span><span class="chip">P ${m.protein}غ</span><span class="chip">C ${m.carbs}غ</span><span class="chip">F ${m.fat}غ</span></div></div>`).join(''):`<div class="empty">لم تسجل وجبات اليوم بعد.</div>`}
function renderMeasurements(){const arr=[...data.measurements].sort((a,b)=>b.date.localeCompare(a.date));document.querySelector('#measurementList').innerHTML=arr.map((m,i)=>`<div class="stack-item"><div class="stack-item-head"><div><h4>${esc(m.weight)} كجم</h4><p class="muted">${fmtDate(m.date)}</p></div><button class="secondary" onclick="editRecord('measurement',${i})">تعديل</button><button class="secondary" onclick="removeMeasurement(${i})">حذف</button></div><div class="chips"><span class="chip">BMI ${esc(m.bmi??"—")}</span><span class="chip">دهون ${esc(m.bfr??"—")}%</span><span class="chip">عضلات ${esc(m.muscleWeight??"—")} كجم</span><span class="chip">ماء ${esc(m.water??"—")}%</span><span class="chip">BMR ${esc(m.bmr??"—")}</span></div></div>`).join('')}
function renderAll(){renderDashboard();renderWorkouts();renderNutrition();renderMeasurements()}
function fieldsHtml(fields){return fields.map(f=>`<div class="field ${f.full?'full':''}"><label for="field-${f.name}">${f.label}</label><input id="field-${f.name}" name="${f.name}" type="${f.type||'text'}" step="${f.step||'any'}" value="${esc(f.value??'')}" ${f.type==='number'?`min="${f.name==='weight'||f.name.startsWith('r')?0.1:0}"`:""} required></div>`).join('')}
function openModal(type){editing=null;const modal=document.querySelector('#modal'),fields=document.querySelector('#modalFields');modal.dataset.type=type;if(type==='measurement'){document.querySelector('#modalTitle').textContent='قياس جديد';fields.innerHTML=fieldsHtml([{label:'التاريخ',name:'date',type:'date',value:selectedDate},{label:'الوزن (كجم)',name:'weight',type:'number'},{label:'BMI',name:'bmi',type:'number'},{label:'دهون الجسم %',name:'bfr',type:'number'},{label:'كتلة الدهون كجم',name:'fatMass',type:'number'},{label:'وزن العضلات كجم',name:'muscleWeight',type:'number'},{label:'الماء %',name:'water',type:'number'},{label:'BMR',name:'bmr',type:'number'},{label:'دهون حشوية',name:'visceralFat',type:'number'},{label:'وزن دون دهون',name:'leanWeight',type:'number'}])}else if(type==='meal'){document.querySelector('#modalTitle').textContent='إضافة وجبة';fields.innerHTML=fieldsHtml([{label:'التاريخ',name:'date',type:'date',value:selectedDate},{label:'اسم الوجبة',name:'name'},{label:'مكونات الوجبة',name:'food',full:true},{label:'السعرات',name:'calories',type:'number'},{label:'البروتين (غ)',name:'protein',type:'number'},{label:'الكربوهيدرات (غ)',name:'carbs',type:'number'},{label:'الدهون (غ)',name:'fat',type:'number'}])}else{document.querySelector('#modalTitle').textContent='تمرين جديد';fields.innerHTML=fieldsHtml([{label:'التاريخ',name:'date',type:'date',value:selectedDate},{label:'المجموعة العضلية',name:'group'},{label:'التمرين',name:'exercise',full:true},{label:'مجموعة 1 وزن',name:'w1',type:'number'},{label:'عدات',name:'r1',type:'number'},{label:'مجموعة 2 وزن',name:'w2',type:'number'},{label:'عدات',name:'r2',type:'number'},{label:'مجموعة 3 وزن',name:'w3',type:'number'},{label:'عدات',name:'r3',type:'number'}])}if(type==='measurement')fields.querySelectorAll('input').forEach(i=>{if(!['date','weight'].includes(i.name))i.required=false});fields.querySelectorAll('input[name^=r]').forEach(i=>{i.step='1';i.min='1'});modal.showModal()}
window.removeWorkout=i=>{if(!confirm('حذف هذا التمرين؟'))return;const arr=[...data.workouts].sort((a,b)=>b.date.localeCompare(a.date));const target=arr[i];data.workouts=data.workouts.filter(x=>x!==target);save()};window.removeMeal=i=>{if(!confirm('حذف هذه الوجبة؟'))return;const today=selectedDate,arr=data.meals.filter(m=>m.date===today);data.meals=data.meals.filter(x=>x!==arr[i]);save()};window.removeMeasurement=i=>{if(!confirm('حذف هذا القياس؟'))return;const arr=[...data.measurements].sort((a,b)=>b.date.localeCompare(a.date));data.measurements=data.measurements.filter(x=>x!==arr[i]);save()};
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active')}));
document.querySelector('#newWorkoutBtn').onclick=()=>openModal('workout');document.querySelector('#newMealBtn').onclick=()=>openModal('meal');document.querySelector('#newMeasurementBtn').onclick=()=>openModal('measurement');
document.querySelector('#modalForm').addEventListener('submit',e=>{e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries()),type=document.querySelector('#modal').dataset.type;if(type==='settings'){data.goalWeight=+fd.goalWeight||null;data.targets=Object.fromEntries(['calories','protein','carbs','fat'].map(k=>[k,+fd[k]||null]));}else if(type==='measurement'){['weight','bmi','bfr','fatMass','muscleWeight','water','bmr','visceralFat','leanWeight'].forEach(k=>fd[k]=fd[k]===''?null:+fd[k]);if(editing)Object.assign(editing,fd);else data.measurements.push(fd)}else if(type==='meal'){['calories','protein','carbs','fat'].forEach(k=>fd[k]=fd[k]===''?null:+fd[k]);if(editing)Object.assign(editing,fd);else data.meals.push(fd)}else{const record={date:fd.date,group:fd.group,exercise:fd.exercise,sets:[{w:+fd.w1,r:+fd.r1},{w:+fd.w2,r:+fd.r2},{w:+fd.w3,r:+fd.r3}]};if(editing)Object.assign(editing,record);else data.workouts.push(record)}document.querySelector('#modal').close();e.target.reset();save()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.querySelector('#installBtn').classList.remove('hidden')});document.querySelector('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}};


window.editRecord=(type,i)=>{const key={workout:'workouts',meal:'meals',measurement:'measurements'}[type];const arr=type==='meal'?data.meals.filter(x=>x.date===selectedDate):[...data[key]].sort((a,b)=>b.date.localeCompare(a.date));const record=arr[i];openModal(type);editing=record;document.querySelector('#modalTitle').textContent='تعديل السجل';const values={...record};record.sets?.forEach((s,i)=>{values['w'+(i+1)]=s.w;values['r'+(i+1)]=s.r});for(const input of document.querySelectorAll('#modalFields input'))input.value=values[input.name]??'';};
document.querySelector('#logDate').value=selectedDate;
document.querySelector('#logDate').onchange=e=>{if(e.target.value){selectedDate=e.target.value;renderAll()}};
document.querySelector('#todayBtn').onclick=()=>{selectedDate=localDate();document.querySelector('#logDate').value=selectedDate;renderAll()};
document.querySelector('#settingsBtn').onclick=()=>{editing=null;const modal=document.querySelector('#modal');modal.dataset.type='settings';document.querySelector('#modalTitle').textContent='أهدافك الشخصية';document.querySelector('#modalFields').innerHTML=fieldsHtml([{name:'goalWeight',label:'هدف الوزن (كجم)',type:'number',value:data.goalWeight},...['calories','protein','carbs','fat'].map((k,i)=>({name:k,label:['السعرات اليومية','البروتين (غ)','الكربوهيدرات (غ)','الدهون (غ)'][i],type:'number',value:data.targets[k]}))]);document.querySelectorAll('#modalFields input').forEach(i=>{i.required=false;i.min=1});modal.showModal()};
document.querySelector('#exportBtn').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='fitness-backup-'+localDate()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
document.querySelector('#importFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw Error();const candidate=JSON.parse(await file.text());const number=x=>typeof x==='number'&&Number.isFinite(x)&&x>=0;const date=x=>typeof x==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(x)&&!isNaN(new Date(x+'T12:00:00').getTime());if(!candidate||!['measurements','workouts','meals'].every(k=>Array.isArray(candidate[k])&&candidate[k].every(x=>x&&date(x.date)))||!candidate.measurements.every(x=>number(x.weight)&&x.weight>0&&['bmi','bfr','fatMass','muscleWeight','water','bmr','visceralFat','leanWeight'].every(k=>x[k]==null||number(x[k])))||!candidate.workouts.every(x=>typeof x.exercise==='string'&&typeof x.group==='string'&&Array.isArray(x.sets)&&x.sets.every(s=>number(s.w)&&number(s.r)&&s.r>=1&&Number.isInteger(s.r)))||!candidate.meals.every(x=>typeof x.name==='string'&&typeof x.food==='string'&&['calories','protein','carbs','fat'].every(k=>number(x[k])))||!candidate.targets||!['calories','protein','carbs','fat'].every(k=>candidate.targets[k]===null||number(candidate.targets[k]))||(candidate.goalWeight!==null&&!number(candidate.goalWeight)))throw Error();if(confirm('استبدال السجل الحالي بالنسخة المستوردة؟ يفضل تصدير نسخة من سجلك الحالي أولًا.')){data=candidate;save()}}catch{document.querySelector('#notice').textContent='الملف غير صالح. اختر نسخة احتياطية صادرة من التطبيق.'}finally{e.target.value=''}};
renderAll();
